name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  elf:
    runs-on: ubuntu-latest
    name: Build Practice Mod ELFs

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Build
        run: ./build.sh Release

      - name: Upload elf
        uses: actions/upload-artifact@v7
        with:
          name: Release Elf
          if-no-files-found: error
          path: |
            cmake-build-release-docker/prime2-practice
            cmake-build-release-docker/prime2-practice.map
