name: Build pyinstaller for windows

on:
  workflow_dispatch:

jobs:
  build_installer:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run pyinstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade PyInstaller
          cd patcher
          pyinstaller --onefile main.py

      - uses: actions/upload-artifact@v4
        with:
          name: main.exe
          path: patcher/dist/main.exe
          if-no-files-found: error
